# Generated by Django 4.1.13 on 2025-12-09 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Recompensa',
                'verbose_name_plural': 'Categorías de Recompensa',
            },
        ),
        migrations.CreateModel(
            name='MaterialValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_por_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Valor',
                'verbose_name_plural': 'Materiales Valor',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puntos_minimos', models.IntegerField()),
                ('puntos_maximos', models.IntegerField()),
                ('imagen_insignia', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rango',
                'verbose_name_plural': 'Rangos',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_puntos', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Incentivos.categoriarecompensa')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='Recolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rango_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Incentivos.rango')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recolector',
                'verbose_name_plural': 'Recolectores',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrega', models.DateTimeField(auto_now_add=True)),
                ('total_puntos_obtenidos', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='completado', max_length=20)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_encargado', to=settings.AUTH_USER_MODEL)),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incentivos.recolector')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Incentivos.entrega')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incentivos.materialvalor')),
            ],
            options={
                'verbose_name': 'Detalle de Entrega',
                'verbose_name_plural': 'Detalles de Entrega',
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('puntos_gastados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('codigo_retiro', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incentivos.recolector')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incentivos.recompensa')),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
            },
        ),
    ]
