# Generated by Django 5.2.8 on 2026-01-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incentivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleentrega',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='materialvalor',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='recolector',
            name='fecha_actualizacion',
        ),
    ]
