# Generated by Django 5.2.8 on 2026-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incentivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
