# Generated by Django 5.2.8 on 2026-01-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incentivos', '0002_remove_detalleentrega_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recompensas/'),
        ),
    ]
