# Generated by Django 5.2.8 on 2026-01-13 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incentivos', '0003_alter_recompensa_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrega',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialvalor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recolector',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
