# Generated by Django 5.2.8 on 2026-01-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incentivos', '0004_detalleentrega_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recompensas/', verbose_name='Imagen de la recompensa'),
        ),
    ]
