# Generated by Django 5.2.8 on 2025-12-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id_categoria_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria_gastos',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gastos', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('factura_adjunto', models.CharField(max_length=150)),
                ('id_categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ingresos.categoriagasto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.usuario')),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('estado_orden', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], max_length=20)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.usuario')),
            ],
            options={
                'db_table': 'orden_venta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], max_length=20)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ingresos.ordenventa')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='VentaExterna',
            fields=[
                ('id_venta_externa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('cliente_nombre', models.CharField(max_length=50)),
                ('cliente_contacto', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.usuario')),
            ],
            options={
                'db_table': 'venta_externa',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaExterna',
            fields=[
                ('id_detalle_venta_ex', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.CharField(choices=[('1', 'Plástico'), ('2', 'Metal'), ('3', 'Papel'), ('4', 'Otro')], max_length=1)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_venta_externa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ingresos.ventaexterna')),
            ],
            options={
                'db_table': 'detalle_venta_externa',
            },
        ),
    ]
