# Generated by Django 5.2.8 on 2026-01-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventaexterna',
            name='subtotal',
        ),
    ]
