# Generated by Django 5.2.8 on 2026-01-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0002_remove_detalleventaexterna_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='factura_adjunto',
        ),
    ]
