# Generated by Django 5.2.8 on 2026-01-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0003_remove_gastos_factura_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_orden',
        ),
        migrations.DeleteModel(
            name='OrdenVenta',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
