# Generated by Django 5.2.8 on 2025-12-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('admin', 'Administrador')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=80)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['rol'], name='MarketPlace_rol_350336_idx'), models.Index(fields=['fecha_registro'], name='MarketPlace_fecha_r_336db9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_disponible_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pureza', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=5)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], max_length=15)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.categoria')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.usuario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_orden', models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='MarketPlace.usuario')),
                ('id_usuario_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to='MarketPlace.usuario')),
            ],
            options={
                'verbose_name': 'Orden de venta',
                'verbose_name_plural': 'Órdenes de venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('id_conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.conversacion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='id_usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_enviadas', to='MarketPlace.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='id_usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_recibidas', to='MarketPlace.usuario'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], max_length=15)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.ordenventa')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['id_orden'], name='MarketPlace_id_orde_d635b1_idx'), models.Index(fields=['estado_pago'], name='MarketPlace_estado__7ebb09_idx'), models.Index(fields=['metodo_pago'], name='MarketPlace_metodo__7700df_idx'), models.Index(fields=['fecha'], name='MarketPlace_fecha_468b65_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='monto_positivo')],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.producto')),
            ],
            options={
                'verbose_name': 'Item de carrito',
                'verbose_name_plural': 'Items de carrito',
                'ordering': ['id_carrito', 'id_item'],
                'indexes': [models.Index(fields=['id_carrito'], name='MarketPlace_id_carr_9a7325_idx'), models.Index(fields=['id_producto'], name='MarketPlace_id_prod_134257_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_kg__gt', 0)), name='cantidad_positiva'), models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='precio_unitario_positivo')],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('orden', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='MarketPlace.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['id_producto', 'orden'],
                'unique_together': {('id_producto', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.ordenventa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.producto')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'verbose_name_plural': 'Detalles de orden',
                'ordering': ['id_orden', 'id_detalle'],
                'indexes': [models.Index(fields=['id_orden'], name='MarketPlace_id_orde_e08a54_idx'), models.Index(fields=['id_producto'], name='MarketPlace_id_prod_71a9ba_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_kg__gt', 0)), name='detalle_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalle_precio_positivo')],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='MarketPlace_estado_b77e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['pureza'], name='MarketPlace_pureza_5b2b46_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio_kg'], name='MarketPlace_precio__4ce7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['id_categoria'], name='MarketPlace_id_cate_595cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['fecha_publicacion'], name='MarketPlace_fecha_p_1492d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_kg__gte', 0)), name='precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('peso_disponible_kg__gte', 0)), name='peso_positivo'),
        ),
        migrations.AddIndex(
            model_name='ordenventa',
            index=models.Index(fields=['id_usuario_vendedor'], name='MarketPlace_id_usua_96ce94_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenventa',
            index=models.Index(fields=['id_usuario_comprador'], name='MarketPlace_id_usua_bd7f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenventa',
            index=models.Index(fields=['estado_orden'], name='MarketPlace_estado__1830b5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenventa',
            index=models.Index(fields=['fecha'], name='MarketPlace_fecha_ea1ccb_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordenventa',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='total_positivo'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['id_conversacion'], name='MarketPlace_id_conv_08e174_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['id_usuario'], name='MarketPlace_id_usua_4bca6c_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['fecha_hora'], name='MarketPlace_fecha_h_441d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['leido'], name='MarketPlace_leido_dffe22_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['id_usuario1'], name='MarketPlace_id_usua_cce9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['id_usuario2'], name='MarketPlace_id_usua_5b9866_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_creacion'], name='MarketPlace_fecha_c_30cdce_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(fields=('id_usuario1', 'id_usuario2'), name='conversacion_unica'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['id_usuario'], name='MarketPlace_id_usua_08f032_idx'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['fecha_creacion'], name='MarketPlace_fecha_c_12c3dd_idx'),
        ),
    ]
