# Generated by Django 5.2.8 on 2026-01-21 02:42

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Categoria = apps.get_model('MarketPlace', 'Categoria')
    default_categories = [
        {"nombre": "Papel", "descripcion": "Productos reciclables de papel"},
        {"nombre": "Plástico", "descripcion": "Productos reciclables de plástico"},
        {"nombre": "Cartón", "descripcion": "Productos reciclables de Cartón"},
        {"nombre": "Metal", "descripcion": "Productos reciclables de metal"},
        {"nombre": "Vidrio", "descripcion": "Productos reciclables de Vidrio"},
    ]
    for cat in default_categories:
        Categoria.objects.get_or_create(
            nombre=cat['nombre'],
            defaults={"descripcion": cat['descripcion']}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
