# Generated by Django 5.2.8 on 2025-12-03 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='imagenproducto',
            name='MarketPlace_id_prod_c32858_idx',
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(default='None', upload_to='productos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='MarketPlace.producto'),
        ),
    ]
