# Generated by Django 5.2.8 on 2026-01-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='datos_pago',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('otro', 'Otro')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['transaccion_id'], name='MarketPlace_transac_4600ee_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['paypal_payment_id'], name='MarketPlace_paypal__32cbd4_idx'),
        ),
    ]
