# Generated by Django 5.2.8 on 2026-01-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0002_pago_datos_pago_pago_paypal_payer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='teléfono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
