# Generated by Django 5.2.8 on 2026-01-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0002_pago_datos_pago_pago_paypal_payer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='teléfono',
        ),
    ]
