# Generated by Django 5.2.8 on 2026-04-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0002_auto_20260120_2042'),
    ]

    operations = [
    ]
