# Generated by Django 5.2.8 on 2026-01-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0003_remove_usuario_telefono_usuario_teléfono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
