# Generated by Django 5.2.8 on 2026-01-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0003_rename_telefono_usuario_teléfono'),
        ('MarketPlace', '0004_rename_teléfono_usuario_telefono'),
    ]

    operations = [
    ]
