# Generated by Django 5.2.8 on 2026-01-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0005_merge_20260118_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
